name: Test Workflow

on: 
  push: # Trigger on push to any branch
    branches:
      - "*"  # Will trigger on pushes to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello, world!"
